bool read_u8(uint8_t **data, size_t *len, uint8_t *out);
bool read_u16(uint8_t **data, size_t *len, uint16_t *out);
bool read_u32(uint8_t **data, size_t *len, uint32_t *out);
bool read_u64(uint8_t **data, size_t *len, uint64_t *out);
bool read_i8(uint8_t **data, size_t *len, int8_t *out);
bool read_i16(uint8_t **data, size_t *len, int16_t *out);
bool read_i32(uint8_t **data, size_t *len, int32_t *out);
bool read_i64(uint8_t **data, size_t *len, int64_t *out);
bool read_u16be(uint8_t **data, size_t *len, uint16_t *out);
bool read_u32be(uint8_t **data, size_t *len, uint32_t *out);
bool read_u64be(uint8_t **data, size_t *len, uint64_t *out);
bool read_i16be(uint8_t **data, size_t *len, int16_t *out);
bool read_i32be(uint8_t **data, size_t *len, int32_t *out);
bool read_i64be(uint8_t **data, size_t *len, int64_t *out);
bool slice_bytes(uint8_t **data, size_t *len, uint8_t **out, size_t size);
bool read_bytes(uint8_t **data, size_t *len, uint8_t *out, size_t size);
bool alloc_bytes(uint8_t **data, size_t *len, uint8_t **out, size_t size);
bool slice_ascii(uint8_t **data, size_t *len, char **out, size_t size);
bool read_ascii(uint8_t **data, size_t *len, char *out, size_t size);
bool alloc_ascii(uint8_t **data, size_t *len, char **out, size_t size);
size_t write_u8(uint8_t **data, uint8_t out);
size_t write_u16(uint8_t **data, uint16_t out);
size_t write_u32(uint8_t **data, uint32_t out);
size_t write_u64(uint8_t **data, uint64_t out);
size_t write_i8(uint8_t **data, int8_t out);
size_t write_i16(uint8_t **data, int16_t out);
size_t write_i32(uint8_t **data, int32_t out);
size_t write_i64(uint8_t **data, int64_t out);
size_t write_u16be(uint8_t **data, uint16_t out);
size_t write_u32be(uint8_t **data, uint32_t out);
size_t write_u64be(uint8_t **data, uint64_t out);
size_t write_i16be(uint8_t **data, int16_t out);
size_t write_i32be(uint8_t **data, int32_t out);
size_t write_i64be(uint8_t **data, int64_t out);
size_t write_bytes(uint8_t **data, const uint8_t *bytes, size_t size);
bool read_varint(uint8_t **data, size_t *data_len, uint64_t *value);
bool read_varsize(uint8_t **data, size_t *data_len, size_t *value);
bool size_varint(uint64_t value);
size_t size_varsize(size_t value);
size_t write_varint(uint8_t **data, uint64_t size);
size_t write_varsize(uint8_t **data, size_t size);
bool slice_varbytes( uint8_t **data, size_t *data_len, uint8_t **out, size_t *out_len);
bool read_varbytes( uint8_t **data, size_t *data_len, uint8_t *out, size_t out_size, size_t *out_len);
bool alloc_varbytes( uint8_t **data, size_t *data_len, uint8_t **out, size_t *out_len);
size_t size_varbytes(size_t size);
size_t write_varbytes(uint8_t **data, const uint8_t *bytes, size_t size);
uint8_t get_u8(const uint8_t *data);
uint16_t get_u16(const uint8_t *data);
uint32_t get_u32(const uint8_t *data);
uint64_t get_u64(const uint8_t *data);
int8_t get_i8(const uint8_t *data);
int16_t get_i16(const uint8_t *data);
int32_t get_i32(const uint8_t *data);
int64_t get_i64(const uint8_t *data);
uint16_t get_u16be(const uint8_t *data);
uint32_t get_u32be(const uint8_t *data);
uint64_t get_u64be(const uint8_t *data);
int16_t get_i16be(const uint8_t *data);
int32_t get_i32be(const uint8_t *data);
int64_t get_i64be(const uint8_t *data);
void set_u8(uint8_t *data, uint8_t out);
void set_u16(uint8_t *data, uint16_t out);
void set_u32(uint8_t *data, uint32_t out);
void set_u64(uint8_t *data, uint64_t out);
void set_i8(uint8_t *data, int8_t out);
void set_i16(uint8_t *data, int16_t out);
void set_i32(uint8_t *data, int32_t out);
void set_i64(uint8_t *data, int64_t out);
void set_u16be(uint8_t *data, uint16_t out);
void set_u32be(uint8_t *data, uint32_t out);
void set_u64be(uint8_t *data, uint64_t out);
void set_i16be(uint8_t *data, int16_t out);
void set_i32be(uint8_t *data, int32_t out);
void set_i64be(uint8_t *data, int64_t out);
